Use code instead of message to detect unauth, since sometimes i got this message:
ws_api.exceptions.WSApiException: GraphQL query failed: FetchSecuritySearchResult; Response: {'errors': [{'message': 'Not Authorized', 'extensions': {'code': 'UNAUTHENTICATED'}}]}
Failed to run task: exit status 1

which does not have . in the end of Not Authroized.